# permissions for end users to view githubrunnerautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubrunnerautoscaler-viewer-role
rules:
- apiGroups:
  - operator.hurb.com
  resources:
  - githubrunnerautoscalers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.hurb.com
  resources:
  - githubrunnerautoscalers/status
  verbs:
  - get
