# permissions for end users to edit githubrunnerautoscalers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: githubrunnerautoscaler-editor-role
rules:
- apiGroups:
  - operator.hurb.com
  resources:
  - githubrunnerautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.hurb.com
  resources:
  - githubrunnerautoscalers/status
  verbs:
  - get
