---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.hurb.com
  resources:
  - githubrunnerautoscalers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.hurb.com
  resources:
  - githubrunnerautoscalers/finalizers
  verbs:
  - update
- apiGroups:
  - operator.hurb.com
  resources:
  - githubrunnerautoscalers/status
  verbs:
  - get
  - patch
  - update
