apiVersion: operator.hurb.com/v1alpha1
kind: GithubRunnerAutoscaler
metadata:
  name: githubrunnerautoscaler-test
spec:
  deploymentName: runner
  minWorkers: 5
  namespace: default
  orgName: orgname
  githubToken:
    secretName: github-token
    keyRef: token

---

apiVersion: v1
stringData:
  token: "{{.Token}}"
kind: Secret
metadata:
  name: github-token

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: runner
  name: runner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: runner
  strategy: {}
  template:
    metadata:
      labels:
        app: runner
    spec:
      containers:
      - image: busybox
        name: busybox
        command: ["/bin/sh","-c","while true; do sleep 10; done"]

