//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2022.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubRunnerAutoscaler) DeepCopyInto(out *GithubRunnerAutoscaler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubRunnerAutoscaler.
func (in *GithubRunnerAutoscaler) DeepCopy() *GithubRunnerAutoscaler {
	if in == nil {
		return nil
	}
	out := new(GithubRunnerAutoscaler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubRunnerAutoscaler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubRunnerAutoscalerList) DeepCopyInto(out *GithubRunnerAutoscalerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]GithubRunnerAutoscaler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubRunnerAutoscalerList.
func (in *GithubRunnerAutoscalerList) DeepCopy() *GithubRunnerAutoscalerList {
	if in == nil {
		return nil
	}
	out := new(GithubRunnerAutoscalerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *GithubRunnerAutoscalerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubRunnerAutoscalerSpec) DeepCopyInto(out *GithubRunnerAutoscalerSpec) {
	*out = *in
	if in.GithubToken != nil {
		in, out := &in.GithubToken, &out.GithubToken
		*out = new(GithubTokenSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubRunnerAutoscalerSpec.
func (in *GithubRunnerAutoscalerSpec) DeepCopy() *GithubRunnerAutoscalerSpec {
	if in == nil {
		return nil
	}
	out := new(GithubRunnerAutoscalerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubRunnerAutoscalerStatus) DeepCopyInto(out *GithubRunnerAutoscalerStatus) {
	*out = *in
	in.LastUpdateTime.DeepCopyInto(&out.LastUpdateTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubRunnerAutoscalerStatus.
func (in *GithubRunnerAutoscalerStatus) DeepCopy() *GithubRunnerAutoscalerStatus {
	if in == nil {
		return nil
	}
	out := new(GithubRunnerAutoscalerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GithubTokenSpec) DeepCopyInto(out *GithubTokenSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GithubTokenSpec.
func (in *GithubTokenSpec) DeepCopy() *GithubTokenSpec {
	if in == nil {
		return nil
	}
	out := new(GithubTokenSpec)
	in.DeepCopyInto(out)
	return out
}
